version: '3.8'

services:
  # Next.js アプリケーション（開発環境）
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/spoon_app_dev
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - TWITTER_CLIENT_ID=your-twitter-client-id
      - TWITTER_CLIENT_SECRET=your-twitter-client-secret
      - FACEBOOK_CLIENT_ID=your-facebook-client-id
      - FACEBOOK_CLIENT_SECRET=your-facebook-client-secret
      - STRIPE_SECRET_KEY=sk_test_your-stripe-secret-key
      - STRIPE_PUBLISHABLE_KEY=pk_test_your-stripe-publishable-key
      - OPENAI_API_KEY=your-openai-api-key
      - UPLOAD_DIR=/app/uploads
    volumes:
      - .:/app
      - /app/node_modules
      - uploads:/app/uploads
    depends_on:
      - db
      - redis
    networks:
      - spoon-network

  # PostgreSQL データベース
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=spoon_app_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - spoon-network

  # Redis キャッシュ
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - spoon-network

  # pgAdmin（データベース管理ツール）
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - spoon-network

  # MinIO（S3互換オブジェクトストレージ）
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - spoon-network

volumes:
  postgres_data:
  redis_data:
  minio_data:
  uploads:

networks:
  spoon-network:
    driver: bridge
